# Generated by Django 4.2.30 on 2026-09-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_minutes', models.IntegerField(blank=True, help_text='Max total screen time per day (minutes).', null=True)),
                ('weekend_limit_minutes', models.IntegerField(blank=True, help_text='Override limit for weekends (minutes).', null=True)),
                ('allowed_start', models.TimeField(blank=True, help_text='Start of allowed usage window.', null=True)),
                ('allowed_end', models.TimeField(blank=True, help_text='End of allowed usage window.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_policy', to='accounts.childprofile')),
            ],
            options={
                'verbose_name': 'Screen Time Policy',
                'verbose_name_plural': 'Screen Time Policies',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Application name (case-insensitive match)', max_length=100)),
                ('policy', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('LIMITED', 'Limited (time-based)')], default='ALLOW', max_length=10)),
                ('daily_limit_minutes', models.IntegerField(blank=True, help_text='Used only when policy=LIMITED. Max minutes per day.', null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_policies', to='accounts.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_policies', to='accounts.parentprofile')),
            ],
            options={
                'verbose_name': 'Application Policy',
                'verbose_name_plural': 'Application Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('safe', 'Safe'), ('adult', 'Adult / Inappropriate'), ('gambling', 'Gambling'), ('violence', 'Violence'), ('phishing', 'Phishing'), ('malware', 'Malware / Suspicious'), ('social_media', 'Social Media'), ('gaming', 'Gaming'), ('unknown', 'Unknown')], max_length=30)),
                ('rule_type', models.CharField(choices=[('BLOCK', 'Block'), ('ALLOW', 'Allow (whitelist override)'), ('WARN', 'Warn (show warning, allow through)')], max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Optional note for this rule.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_policies', to='accounts.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_policies', to='accounts.parentprofile')),
            ],
            options={
                'verbose_name': 'Website Policy',
                'verbose_name_plural': 'Website Policies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'domain'], name='policies_we_parent__8b1237_idx'), models.Index(fields=['parent', 'category'], name='policies_we_parent__aefbaf_idx')],
            },
        ),
    ]
