# Generated by Django 4.2.30 on 2026-09-09 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('WEBSITE_VISITED', 'Website Visited'), ('WEBSITE_BLOCKED', 'Website Blocked'), ('WEBSITE_WARNING', 'Website Warning'), ('PHISHING_DETECTED', 'Phishing Detected'), ('CONTENT_FLAGGED', 'Content Flagged'), ('CYBERBULLYING_DETECTED', 'Cyberbullying Detected'), ('GROOMING_RISK_DETECTED', 'Grooming Risk Detected'), ('APPLICATION_STARTED', 'Application Started'), ('APPLICATION_BLOCKED', 'Application Blocked'), ('APPLICATION_LIMITED', 'Application Usage Limited'), ('DOWNLOAD_ATTEMPTED', 'Download Attempted'), ('DOWNLOAD_BLOCKED', 'Download Blocked'), ('SCREEN_TIME_WARNING', 'Screen Time Warning'), ('SCREEN_TIME_LIMIT_REACHED', 'Screen Time Limit Reached'), ('POLICY_CHANGED', 'Policy Changed'), ('AI_ANALYSIS_FAILED', 'AI Analysis Failed')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('url_path', models.CharField(blank=True, help_text='URL path without query string — avoids capturing sensitive query params.', max_length=512)),
                ('app_name', models.CharField(blank=True, max_length=100)),
                ('action_taken', models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLUR', 'Blur'), ('BLOCK', 'Block'), ('LOG', 'Log Only')], max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.device')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('TEXT', 'Text Content'), ('URL', 'URL'), ('IMAGE', 'Image')], max_length=10)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('recommended_action', models.CharField(max_length=10)),
                ('inference_mode', models.CharField(choices=[('REAL', 'Real'), ('MOCK', 'Mock')], default='MOCK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='accounts.device')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_type', models.CharField(db_index=True, max_length=50)),
                ('risk_score', models.FloatField(help_text='0.0 (safe) to 1.0 (definite threat)')),
                ('confidence', models.FloatField(help_text='Model confidence in the classification (0.0–1.0)')),
                ('ai_category', models.CharField(max_length=100)),
                ('indicators', models.JSONField(default=list, help_text='Explainable indicators — e.g. ["contains_sexual_content", "suspicious_domain"]')),
                ('inference_mode', models.CharField(choices=[('REAL', 'Real ONNX Inference'), ('MOCK', 'Mock/Development Heuristic')], default='MOCK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threat_event', to='monitoring.activitylog')),
            ],
            options={
                'verbose_name': 'Threat Event',
                'verbose_name_plural': 'Threat Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['threat_type', 'created_at'], name='monitoring__threat__a98d51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_minutes', models.IntegerField(default=0)),
                ('app_breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_usage', to='accounts.device')),
            ],
            options={
                'verbose_name': 'Screen Time Usage',
                'verbose_name_plural': 'Screen Time Usage Records',
                'indexes': [models.Index(fields=['device', 'date'], name='monitoring__device__b36926_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['device', 'timestamp'], name='monitoring__device__c2a685_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['event_type', 'timestamp'], name='monitoring__event_t_3e7281_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', 'timestamp'], name='monitoring__severit_503dda_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['domain'], name='monitoring__domain_6977b9_idx'),
        ),
    ]
