# Generated by Django 4.2.30 on 2026-09-09 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('PHISHING', 'Phishing Detected'), ('CYBERBULLYING', 'Cyberbullying Detected'), ('GROOMING_RISK', 'Grooming Risk Detected'), ('HARMFUL_CONTENT', 'Harmful Content'), ('SUSPICIOUS_DOWNLOAD', 'Suspicious Download'), ('APP_BLOCKED', 'Application Blocked'), ('SCREEN_TIME', 'Screen Time Limit'), ('WEBSITE_BLOCKED', 'Website Blocked'), ('SYSTEM', 'System Alert')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.activitylog')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.parentprofile')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'is_read', 'created_at'], name='alerts_aler_parent__7d6755_idx'), models.Index(fields=['parent', 'alert_type'], name='alerts_aler_parent__b8a0ec_idx')],
            },
        ),
    ]
